import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClientProvider } from "@tanstack/react-query";

import { routeTree } from "./routeTree.gen";
import { queryClient } from "./lib/queryClient";
import { ToastProvider } from "./components/Toast";
import { setUnauthorizedHandler, LOGIN_PATH } from "./lib/api";
import { AUTH_QUERY_KEY } from "./lib/auth";
import "./styles.css";

// The route tree is generated by @tanstack/router-plugin from src/routes/.
const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  scrollRestoration: true,
});

// Register the router instance type for fully-typed navigation/links.
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

// Central 401 handling: when any API call returns 401 (an expired/absent
// session), send the browser to the login page via the router (an in-app SPA
// navigation, so no full reload) and drop the cached auth status so the login
// screen re-probes. Guarded against a redirect loop when already on /login.
setUnauthorizedHandler(() => {
  queryClient.invalidateQueries({ queryKey: AUTH_QUERY_KEY });
  if (router.state.location.pathname !== LOGIN_PATH) {
    router.navigate({ to: LOGIN_PATH, replace: true });
  }
});

const rootEl = document.getElementById("root");
if (!rootEl) {
  throw new Error("#root element not found");
}

createRoot(rootEl).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <ToastProvider>
        <RouterProvider router={router} />
      </ToastProvider>
    </QueryClientProvider>
  </StrictMode>,
);
