/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecsNewRouteImport } from './routes/specs.new'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsNewRoute = SpecsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SpecsRoute,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => RunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRoute
  '/repos': typeof ReposRoute
  '/runs': typeof RunsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/targets': typeof TargetsRoute
  '/users': typeof UsersRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/specs/new': typeof SpecsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRoute
  '/repos': typeof ReposRoute
  '/runs': typeof RunsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/targets': typeof TargetsRoute
  '/users': typeof UsersRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/specs/new': typeof SpecsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRoute
  '/repos': typeof ReposRoute
  '/runs': typeof RunsRouteWithChildren
  '/specs': typeof SpecsRouteWithChildren
  '/targets': typeof TargetsRoute
  '/users': typeof UsersRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/specs/new': typeof SpecsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/packs'
    | '/repos'
    | '/runs'
    | '/specs'
    | '/targets'
    | '/users'
    | '/runs/$runId'
    | '/specs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/packs'
    | '/repos'
    | '/runs'
    | '/specs'
    | '/targets'
    | '/users'
    | '/runs/$runId'
    | '/specs/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/packs'
    | '/repos'
    | '/runs'
    | '/specs'
    | '/targets'
    | '/users'
    | '/runs/$runId'
    | '/specs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PacksRoute: typeof PacksRoute
  ReposRoute: typeof ReposRoute
  RunsRoute: typeof RunsRouteWithChildren
  SpecsRoute: typeof SpecsRouteWithChildren
  TargetsRoute: typeof TargetsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs/new': {
      id: '/specs/new'
      path: '/new'
      fullPath: '/specs/new'
      preLoaderRoute: typeof SpecsNewRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof RunsRoute
    }
  }
}

interface RunsRouteChildren {
  RunsRunIdRoute: typeof RunsRunIdRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsRunIdRoute: RunsRunIdRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

interface SpecsRouteChildren {
  SpecsNewRoute: typeof SpecsNewRoute
}

const SpecsRouteChildren: SpecsRouteChildren = {
  SpecsNewRoute: SpecsNewRoute,
}

const SpecsRouteWithChildren = SpecsRoute._addFileChildren(SpecsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PacksRoute: PacksRoute,
  ReposRoute: ReposRoute,
  RunsRoute: RunsRouteWithChildren,
  SpecsRoute: SpecsRouteWithChildren,
  TargetsRoute: TargetsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
